# Generated by Django 5.2.4 on 2025-08-03 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='logim',
            new_name='login',
        ),
    ]
